.TH "lib/ Directory Reference" 3 "Tue Jun 14 2011" "Version 0.6" "libglyr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglyr.h\fP"
.br
.PP

.RI "\fIAll method declaration here. You should only need to include this file. \fP"
.ti -1c
.RI "file \fBtranslate.h\fP"
.br
.PP

.RI "\fI(do not use yet) Methods to interact directly with google translator \fP"
.ti -1c
.RI "file \fBtypes.h\fP"
.br
.PP

.RI "\fIFile containing all definitions used in the external API. \fP"
.in -1c
