.TH "lib/ Directory Reference" 3 "Sun May 22 2011" "Version 0.6" "libglyr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglyr.h\fP"
.br
.ti -1c
.RI "file \fBtranslate.h\fP"
.br
.ti -1c
.RI "file \fBtypes.h\fP"
.br
.in -1c
