.TH "GlyCacheList" 3 "Sun May 22 2011" "Version 0.6" "libglyr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlyCacheList \- 
.PP
The return type of Gly_get, a list of GlyMemCaches.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGlyMemCache\fP ** \fBlist\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int \fBusersig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The return type of Gly_get, a list of GlyMemCaches. 
.SH "Field Documentation"
.PP 
.SS "\fBGlyMemCache\fP** \fBGlyCacheList::list\fP"A list of pointers to \fBGlyMemCache\fP instances, use Gly_clist_at to access those. 
.SS "size_t \fBGlyCacheList::size\fP"Total number of items 
.SS "int \fBGlyCacheList::usersig\fP"Do not use. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libglyr from the source code.
