.TH "GlyrFetcherInfo" 3 "Sun Aug 21 2011" "Version 0.8" "libglyr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlyrFetcherInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "enum \fBGLYR_GET_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBGlyrSourceInfo\fP * \fBhead\fP"
.br
.ti -1c
.RI "struct \fBGlyrFetcherInfo\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBGlyrFetcherInfo\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBGlyrSourceInfo\fP* \fBGlyrFetcherInfo::head\fP"
.SS "char* \fBGlyrFetcherInfo::name\fP"
.SS "struct \fBGlyrFetcherInfo\fP* \fBGlyrFetcherInfo::next\fP"
.SS "struct \fBGlyrFetcherInfo\fP* \fBGlyrFetcherInfo::prev\fP"
.SS "enum \fBGLYR_GET_TYPE\fP \fBGlyrFetcherInfo::type\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libglyr from the source code'\&.
