.TH "GlyrSourceInfo" 3 "Sun Aug 21 2011" "Version 0.8" "libglyr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlyrSourceInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBkey\fP"
.br
.ti -1c
.RI "enum \fBGLYR_GET_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBquality\fP"
.br
.ti -1c
.RI "int \fBspeed\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "struct \fBGlyrSourceInfo\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBGlyrSourceInfo\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char \fBGlyrSourceInfo::key\fP"
.SS "char* \fBGlyrSourceInfo::name\fP"
.SS "struct \fBGlyrSourceInfo\fP* \fBGlyrSourceInfo::next\fP"
.SS "struct \fBGlyrSourceInfo\fP* \fBGlyrSourceInfo::prev\fP"
.SS "int \fBGlyrSourceInfo::quality\fP"
.SS "int \fBGlyrSourceInfo::speed\fP"
.SS "enum \fBGLYR_GET_TYPE\fP \fBGlyrSourceInfo::type\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libglyr from the source code'\&.
