#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>

#include "core.h"
#include "types.h"
#include "stringop.h"

#include "lyrics/lyricswiki.h"
#include "lyrics/magistrix.h"
#include "lyrics/lyrix_at.h"
#include "lyrics/darklyrics.h"
#include "lyrics/lyricsvip.h"
#include "lyrics/directlyrics.h"
#include "lyrics/songlyrics.h"
#include "lyrics/lyrdb.h"
#include "lyrics/metrolyrics.h"

// Add your's here
plugin_t lyric_providers[] =
{
//  full name       key  coloredname    use?    parser callback           geturl callback         free url?
    {"lyricswiki",  "w", "lyricswiki",  false, {lyrics_lyricswiki_parse,  lyrics_lyricswiki_url,  false}},
    {"darklyrics",  "y", "darklyrics",  false, {lyrics_darklyrics_parse,  lyrics_darklyrics_url,  false}},
    {"directlyrics","i", "directlyrics",false, {lyrics_directlyrics_parse,lyrics_directlyrics_url,true }},
    {"songlyrics",  "s", "songlyrics",  false, {lyrics_songlyrics_parse,  lyrics_songlyrics_url,  true }},
    {"lyricsvip",   "v", "lyricsvip",   false, {lyrics_lyricsvip_parse,   lyrics_lyricsvip_url,   true }},
    {"safe",        NULL,NULL,          false, {NULL,                     NULL,                   false}},
    {"lyr.db",      "d", "lyr.db",      false, {lyrics_lyrdb_parse,       lyrics_lyrdb_url,       false}},
    {"lyrix.at",    "a", "lyrix.at",    false, {lyrics_lyrixat_parse,     lyrics_lyrixat_url,     false}},
    {"metrolyrics", "m", "metrolyrics", false, {lyrics_metrolyrics_parse, lyrics_metrolyrics_url, false}},
    {"magistrix",   "x", "magistrix",   false, {lyrics_magistrix_parse,   lyrics_magistrix_url,   false}},
    {"unsafe",      NULL, NULL,         false, {NULL,                     NULL,                   false}},
    { NULL,         NULL, NULL,         false, {NULL,                     NULL,                   false}},
};

plugin_t * glyr_get_lyric_providers(void)
{
    return copy_table(lyric_providers,sizeof(lyric_providers));
}

bool write_lyrics(const char * path, const char * lyrics, const char * artist, const char * album, const char * title)
{
    if(path)
    {
        FILE * handle = fopen(path,"w");
        if(handle)
        {
	    int i, underline = 0;

            underline += printf("\n\"%s\" by \"%s\" ",title,artist);
            if(album)
            {
                underline += printf("from album \"%s\"",album);
            }

	    putchar('\n');	
	    for(i=0; i < underline; i++)
		putchar('-');
	    
	    putchar('\n');	

            fprintf(stdout,"\n%s\n",lyrics);
	    fprintf(handle,"%s\n",lyrics);

            printf("\n-------------------------------------\n");
            printf("# This file was generated by glyr   #\n");
            printf("-------------------------------------\n");
            fclose(handle);

            return true;
        }
    }
    return false;
}


static const char * lyrics_finalize(memCache_t * result, glyr_settings_t * settings, const char * filename)
{
	if(filename)
	{
		char * blyr = beautify_lyrics(result->data);
		if(blyr)
		{
			if(write_lyrics(filename,blyr,settings->artist,settings->album,settings->title) == false)
			{
			    fprintf(stderr,C_R"Unable to write lyrics '"C_"%s"C_R"'\n"C_,filename);
			}
			free(blyr);
		}
	}
        return filename;
}

const char * get_lyrics(glyr_settings_t * settings)
{
    char * filename = strdup_printf("%s/%s-%s.lyr",settings->save_path,settings->artist,settings->title);
    if(filename)
    {
	    if(settings && settings->artist && settings->title)
		return register_and_execute(settings, filename, lyrics_finalize);
	    else
		free(filename);
    }
    else
    {
	    printf(C_R":: "C_"%s is needed to download covers.\n",settings->artist ? "Title" : "Artist");
    }
    return NULL;
}
