#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>

#include "core.h"
#include "types.h"
#include "stringop.h"

#include "lyrics/lyricswiki.h"
#include "lyrics/magistrix.h"
#include "lyrics/lyrix_at.h"
#include "lyrics/darklyrics.h"
#include "lyrics/lyrdb.h"
#include "lyrics/metrolyrics.h"

#define MAX_PLUGINS 10

/*
lyricwiki // done
magistrix // done
lyrix_at  // done
lyricwiki // done

lyricstime.com // woth a try
bluelyrics // worth a try

metrolyrics.com // --possible, though not quite a lot of fun
songlyrics.com  // -- possible ------- but far away from fun

lyrczz // -- possible ---------- todo
lirama.net = Great.. but.. google search? Little content?
lyricslfly... this needs some devel first I guess ;-)
leoslyrics (parser)
darklyrics (parser) - this is just to tell whoever reads this what kind of music im listening too.
*/

#define multi_fprintf(...) fprintf(stderr,__VA_ARGS__); fprintf(handle, __VA_ARGS__)

bool write_lyrics(const char * path, const char * lyrics, const char * artist, const char * album, const char * title)
{
    if(path)
    {
	FILE * handle = fopen(path,"w");
	if(handle)
	{
	    printf("\n");
	    multi_fprintf("\"%s\" by \"%s\" ",artist,title);
	    if(album)
	    {
		multi_fprintf("\nfrom album \"%s\"",album);
	    }

	    multi_fprintf("\n-------------------------------------\n");
	    multi_fprintf("%s\n\n-------------------------------------\n",lyrics);
	    multi_fprintf("# This file was generated by glyr   #\n");
	    multi_fprintf("-------------------------------------\n");
	    fclose(handle);
	    return true;
	}
    }
    return false;
}

// let this be only a local phenomena
#undef multi_fprintf

static char * finalize(cb_object * plugin_list, size_t it, const char * dir, const char *artist, const char * album, const char * title)
{
	// Now do the complex multi download action in the background..
	memCache_t *result = invoke(plugin_list, it, 10,artist,album,title);

	if(result)
	{
		//printf("\n%s",beautify_lyrics(result->data));
		char * path = strdup_printf("%s/%s-%s.lyr",dir,artist,title);
		char * blyr = beautify_lyrics(result->data);
		write_lyrics(path,blyr, artist,album,title);
		return path;
	}
	
	return NULL;
}

char * get_lyrics(const char *artist, const char * album, const char *title, const char *dir,  char update, char max_parallel, const char * order)
{
	if(artist == NULL || title == NULL  )
	{
	   	fprintf(stderr,"(!) %s == NULL",artist?"title":"artist");
		return NULL;
	}

	char * escaped_title  = escape_slashes(title);
	char * escaped_artist = escape_slashes(artist);

	char * filename = NULL;
	if(escaped_artist && escaped_title)
	{
		filename = strdup_printf("%s/%s-%s.lyr",(dir) ? dir : "./",escaped_artist,escaped_title);
		free(escaped_title);
		free(escaped_artist);
	}

	// Check if .lyr is already in dir
	if(update == 0 && access(filename,R_OK) == 0)
	{
		return filename;
	}
	else
	{
		// Re-init
		free(filename);
		filename = NULL;
	}

	// Assume a max. of 10 plugins, just set it higher if you need to.
	cb_object *plugin_list = malloc(sizeof(cb_object) * MAX_PLUGINS);

	// Current plugin
	size_t it = 0;

	// lyrdb is currently (the webiste, not the code) & magistrix fails far too often (wrong lyrics...)
	// Perhaps Mr. Leven can help here

	plugin_init( &plugin_list[it++], lyrics_lyricswiki_url(), lyrics_lyricswiki_parse, 0,0,"lyricswiki");
 	plugin_init( &plugin_list[it++], lyrics_lyrixat_url(), lyrics_lyrixat_parse, 0,0,"lyrix.at");
	plugin_init( &plugin_list[it++], lyrics_darklyrics_url(), lyrics_darklyrics_parse, 0,0,"darklyrics");
	plugin_init( &plugin_list[it++], lyrics_metrolyrics_url(), lyrics_metrolyrics_parse, 0,0,"metrolyrics");

	if( (filename=finalize(plugin_list, it, dir, artist, album, title)) == NULL)
	{
		memset(plugin_list, 0, MAX_PLUGINS * sizeof(cb_object));
		it = 0;
	
		plugin_init( &plugin_list[it++], lyrics_lyrdb_url(), lyrics_lyrdb_parse, 0,0,"lyrdb");
		plugin_init( &plugin_list[it++], lyrics_magistrix_url(), lyrics_magistrix_parse, 0,0,"magistrix");
		
		if( (filename=finalize ( plugin_list, it, filename, artist, album, title)) == NULL)
		{
			puts("== Crap, it failed :(");
		}
	}

	return filename;
}

